import { type NextRequest } from 'next/server';
import {
  sql,
  eq,
  and,
  or,
  isNull,
  isNotNull,
  type SQL,
  type SQLWrapper,
} from 'drizzle-orm';
import { db, type DBTransaction } from '@/lib/db';
import { getPostgresErrorCode } from '@/lib/db/postgres-errors';
import {
  conversations,
  messages,
  patients,
  waMessageStatuses,
  whatsappConnections,
  whatsappContacts,
} from '@/lib/db/schema';
import { appendBackgroundEvent } from '@/lib/events/background';
import { tryPublishOutboxEvent } from '@/lib/events/outbox';
import { markConnectionRevoked } from '@/lib/channels/whatsapp/client';
import { verifySignature } from '@/lib/channels/whatsapp/signature';
import { createLogger, newTraceId } from '@/lib/log';
import {
  whatsappWebhookPayload,
  type WhatsappChangeValue,
} from '@/lib/channels/whatsapp/payload';

export const runtime = 'nodejs';

function requireEnv(name: string): string {
  const value = process.env[name];
  if (!value) throw new Error(`${name} is required`);
  return value;
}

const APP_SECRET = requireEnv('META_APP_SECRET');
const VERIFY_TOKEN = requireEnv('META_WEBHOOK_VERIFY_TOKEN');

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const mode = searchParams.get('hub.mode');
  const token = searchParams.get('hub.verify_token');
  const challenge = searchParams.get('hub.challenge');

  if (mode === 'subscribe' && token === VERIFY_TOKEN) {
    return new Response(challenge, { status: 200 });
  }
  return new Response('Forbidden', { status: 403 });
}

export async function POST(req: NextRequest) {
  const rawBody = await req.text();
  const trace_id = req.headers.get('x-request-id') ?? newTraceId();
  const log = createLogger({ trace_id });
  const header = req.headers.get('x-hub-signature-256');

  if (!verifySignature({ rawBody, header, secret: APP_SECRET })) {
    log.warn('webhook.bad_signature', 'Rejected: invalid webhook signature', {
      hasHeader: header !== null,
    });
    return new Response('Invalid signature', { status: 401 });
  }

  let json: unknown;
  try {
    json = JSON.parse(rawBody);
  } catch {
    log.warn('webhook.invalid_json', 'Rejected: invalid JSON payload');
    return new Response('Bad payload', { status: 400 });
  }

  const parsed = whatsappWebhookPayload.safeParse(json);
  if (!parsed.success) {
    log.warn(
      'webhook.schema_mismatch',
      'Rejected: payload failed schema validation',
      { issue_count: parsed.error.issues.length },
    );
    return new Response('Bad payload', { status: 400 });
  }

  for (const entry of parsed.data.entry) {
    for (const change of entry.changes) {
      switch (change.field) {
        case 'messages':
          await handleMessagesChange(change.value, trace_id);
          await handleStatusesChange(change.value, trace_id);
          break;
        case 'history':
          await handleHistoryChange(change.value, trace_id);
          break;
        case 'smb_app_state_sync':
          await handleAppStateSyncChange(change.value, trace_id);
          break;
        case 'smb_message_echoes':
          await handleMessageEchoesChange(change.value, trace_id);
          break;
        case 'account_update':
          await handleAccountUpdate(entry.id, change.value, trace_id);
          break;
        default:
          break;
      }
    }
  }

  return new Response('EVENT_RECEIVED', { status: 200 });
}

type WebhookConnection = { id: string; ptId: string; wabaId: string };

async function loadConnectionByPhoneNumberId(
  phoneNumberId: string | undefined,
  source: string,
  trace_id: string,
): Promise<WebhookConnection | null> {
  const log = createLogger({ trace_id });
  if (!phoneNumberId) {
    log.warn(
      'webhook.missing_phone_number_id',
      'Webhook payload is missing phone_number_id',
      { source },
    );
    return null;
  }

  const [connection] = await db
    .select({
      id: whatsappConnections.id,
      ptId: whatsappConnections.ptId,
      wabaId: whatsappConnections.wabaId,
    })
    .from(whatsappConnections)
    .where(
      and(
        eq(whatsappConnections.phoneNumberId, phoneNumberId),
        eq(whatsappConnections.status, 'active'),
      ),
    )
    .limit(1);

  if (!connection) {
    log.warn(
      'webhook.unknown_phone_number_id',
      'No active connection for phone_number_id',
      { phone_number_id: phoneNumberId, source },
    );
    return null;
  }
  return connection;
}

// Inbound `type` values that are something the patient actually sent, so they
// open Meta's 24h service window and justify materialising the client +
// conversation rows. `type` is an open string (Meta adds values), so this is an
// allowlist: `system` (number-change notices), `reaction`, `request_welcome` and
// `unsupported` are generated by WhatsApp or too thin to turn an unknown number
// into a permanent entry in the PT's client directory.
const PATIENT_CONTENT_MESSAGE_TYPES = new Set([
  'text',
  'image',
  'audio',
  'video',
  'document',
  'sticker',
  'location',
  'contacts',
  'interactive',
  'button',
  'order',
]);

async function handleMessagesChange(
  value: WhatsappChangeValue,
  trace_id: string,
): Promise<void> {
  const log = createLogger({ trace_id });
  if (value.errors?.some((error) => error.code === 131060)) {
    log.warn(
      'webhook.unsupported_coexistence_request',
      'Unsupported coexistence request',
      { codes: value.errors.map((error) => error.code).filter(Boolean) },
    );
    return;
  }
  const connection = await loadConnectionByPhoneNumberId(
    value.metadata?.phone_number_id,
    'messages',
    trace_id,
  );
  if (!connection) {
    return;
  }
  const { ptId } = connection;

  for (const msg of value.messages ?? []) {
    const contact = value.contacts?.find((c) => c.wa_id === msg.from);
    const name = contact?.profile?.name ?? msg.from;

    // Non-text bodies are not persisted (the engine only reads text), but the
    // inbound still opened Meta's 24h service window. This transaction is the
    // only writer of `last_inbound_at`, so skipping it outright would leave the
    // PWA composer greyed out and PT replies discarded as "window closed".
    if (msg.type !== 'text' || !msg.text) {
      log.warn('webhook.skipping_non_text_message', 'Skipping non-text message', {
        type: msg.type,
        externalId: msg.id,
      });
      if (PATIENT_CONTENT_MESSAGE_TYPES.has(msg.type)) {
        const inboundAt = parseWebhookTimestamp(msg.timestamp);
        await db.transaction(async (tx) => {
          const { conversationId } = await ensureWhatsappConversation(tx, {
            ptId,
            waId: msg.from,
            name,
          });
          await bumpLastInboundAt(tx, conversationId, inboundAt);
        });
      }
      continue;
    }
    const content = msg.text.body;

    const result = await db.transaction(async (tx) => {
      const { conversationId } = await ensureWhatsappConversation(tx, {
        ptId,
        waId: msg.from,
        name,
      });

      const inserted = await tx
        .insert(messages)
        .values({
          ptId,
          conversationId,
          externalId: msg.id,
          role: 'patient',
          channel: 'whatsapp',
          content,
        })
        .onConflictDoNothing({ target: messages.externalId })
        .returning({ id: messages.id });

      if (inserted.length !== 1) return { fresh: false as const };

      await bumpLastInboundAt(tx, conversationId);

      const messageId = inserted[0].id;
      const eventId = await appendBackgroundEvent(tx, {
        type: 'message.received',
        data: {
          messageId,
          ptId,
          conversationId,
          traceId: trace_id,
        },
      });
      return {
        fresh: true as const,
        messageId,
        conversationId,
        eventId,
      };
    });

    if (result.fresh) {
      await tryPublishOutboxEvent(result.eventId);
      log.info('webhook.message_accepted', 'Inbound message accepted', {
        pt_id: ptId,
        conversation_id: result.conversationId,
        message_id: result.messageId,
      });
    }
  }
}

// Monotonic status progression: never let an out-of-order webhook downgrade
// `last_status`. `delivered` and `failed` tie at 2 (mutually-exclusive outcomes
// at the same stage) — the first to arrive holds `last_status`, and neither can
// overwrite `read` (3) nor be overwritten by `sent` (1). Per-status timestamp
// columns are stamped independently (first-write-wins), so `delivered_at` — the
// billing signal — is never lost to a late `failed`.
const WA_STATUS_RANK: Record<string, number> = {
  sent: 1,
  delivered: 2,
  failed: 2,
  read: 3,
};

const WA_STATUS_TS_COLUMN = {
  sent: 'sentAt',
  delivered: 'deliveredAt',
  read: 'readAt',
  failed: 'failedAt',
} as const;

/** `CASE`-based rank of a status expression (column or SQL), per WA_STATUS_RANK. */
function statusRankSql(expr: SQLWrapper): SQL {
  return sql`CASE ${expr} WHEN 'sent' THEN 1 WHEN 'delivered' THEN 2 WHEN 'failed' THEN 2 WHEN 'read' THEN 3 ELSE 0 END`;
}

async function upsertMessageStatus(args: {
  ptId: string;
  status: 'sent' | 'delivered' | 'read' | 'failed';
  ts: Date;
  externalId: string;
  billable: boolean | null;
  pricingCategory: string | null;
  pricingType: string | null;
  pricingModel: string | null;
  errorCode: number | null;
}): Promise<void> {
  const tsColumn = WA_STATUS_TS_COLUMN[args.status];
  await db
    .insert(waMessageStatuses)
    .values({
      ptId: args.ptId,
      externalId: args.externalId,
      lastStatus: args.status,
      sentAt: tsColumn === 'sentAt' ? args.ts : null,
      deliveredAt: tsColumn === 'deliveredAt' ? args.ts : null,
      readAt: tsColumn === 'readAt' ? args.ts : null,
      failedAt: tsColumn === 'failedAt' ? args.ts : null,
      billable: args.billable,
      pricingCategory: args.pricingCategory,
      pricingType: args.pricingType,
      pricingModel: args.pricingModel,
      errorCode: args.errorCode,
    })
    .onConflictDoUpdate({
      target: waMessageStatuses.externalId,
      set: {
        lastStatus: sql`CASE WHEN ${statusRankSql(sql`excluded.last_status`)} > ${statusRankSql(waMessageStatuses.lastStatus)} THEN excluded.last_status ELSE ${waMessageStatuses.lastStatus} END`,
        sentAt: sql`COALESCE(${waMessageStatuses.sentAt}, excluded.sent_at)`,
        deliveredAt: sql`COALESCE(${waMessageStatuses.deliveredAt}, excluded.delivered_at)`,
        readAt: sql`COALESCE(${waMessageStatuses.readAt}, excluded.read_at)`,
        failedAt: sql`COALESCE(${waMessageStatuses.failedAt}, excluded.failed_at)`,
        billable: sql`COALESCE(${waMessageStatuses.billable}, excluded.billable)`,
        pricingCategory: sql`COALESCE(${waMessageStatuses.pricingCategory}, excluded.pricing_category)`,
        pricingType: sql`COALESCE(${waMessageStatuses.pricingType}, excluded.pricing_type)`,
        pricingModel: sql`COALESCE(${waMessageStatuses.pricingModel}, excluded.pricing_model)`,
        errorCode: sql`COALESCE(${waMessageStatuses.errorCode}, excluded.error_code)`,
        updatedAt: sql`now()`,
      },
    });
}

/** First-write-wins: stamp `delivered_at` on the reminder job for this wamid. */
async function markReminderDelivered(
  ptId: string,
  wamid: string,
  ts: Date,
): Promise<void> {
  await db.execute(sql`
    UPDATE reminder_jobs AS rj
    SET delivered_at = ${ts.toISOString()}::timestamptz
    FROM messages AS m
    WHERE m.external_id = ${wamid}
      AND m.pt_id = ${ptId}
      AND rj.message_id = m.id
      AND rj.pt_id = ${ptId}
      AND rj.delivered_at IS NULL
  `);
}

/**
 * A `failed` status for a reminder whose template Meta accepted then dropped:
 * mark the job failed and emit `reminder.failed` (existing push/bell/flag
 * pipeline). Guarded so an already-delivered or already-answered reminder is
 * never re-flagged.
 */
async function failReminderDelivery(args: {
  ptId: string;
  wamid: string;
  reason: string;
  trace_id: string;
}): Promise<void> {
  const log = createLogger({ trace_id: args.trace_id });
  const result = await db.transaction(async (tx) => {
    const affected = await tx.execute<{ appointmentId: string }>(sql`
      UPDATE reminder_jobs AS rj
      SET status = 'failed', last_error = ${args.reason}, skipped_reason = NULL
      FROM messages AS m
      WHERE m.external_id = ${args.wamid}
        AND m.pt_id = ${args.ptId}
        AND rj.message_id = m.id
        AND rj.pt_id = ${args.ptId}
        AND rj.status = 'sent'
        AND rj.delivered_at IS NULL
        AND rj.response_type IS NULL
      RETURNING rj.appointment_id AS "appointmentId"
    `);
    const [row] = affected;
    if (!row) return null;
    const eventId = await appendBackgroundEvent(tx, {
      type: 'reminder.failed',
      data: {
        ptId: args.ptId,
        appointmentId: row.appointmentId,
        reason: args.reason,
        traceId: args.trace_id,
      },
    });
    return { eventId, appointmentId: row.appointmentId };
  });

  if (result) {
    await tryPublishOutboxEvent(result.eventId);
    log.info(
      'webhook.reminder_delivery_failed',
      'Reminder template delivery failed',
      { pt_id: args.ptId, appointment_id: result.appointmentId },
    );
  }
}

async function handleStatusesChange(
  value: WhatsappChangeValue,
  trace_id: string,
): Promise<void> {
  const log = createLogger({ trace_id });
  const statuses = value.statuses ?? [];
  if (statuses.length === 0) return;

  const connection = await loadConnectionByPhoneNumberId(
    value.metadata?.phone_number_id,
    'statuses',
    trace_id,
  );
  if (!connection) return;
  const { ptId } = connection;

  for (const status of statuses) {
    if (!(status.status in WA_STATUS_RANK)) {
      log.warn(
        'webhook.unknown_message_status',
        'Ignoring unrecognized message status',
        { status: status.status, externalId: status.id },
      );
      continue;
    }
    const narrowed = status.status as 'sent' | 'delivered' | 'read' | 'failed';
    const ts = parseWebhookTimestamp(status.timestamp);

    await upsertMessageStatus({
      ptId,
      status: narrowed,
      ts,
      externalId: status.id,
      billable: status.pricing?.billable ?? null,
      pricingCategory: status.pricing?.category ?? null,
      pricingType: status.pricing?.type ?? null,
      pricingModel: status.pricing?.pricing_model ?? null,
      errorCode: status.errors?.[0]?.code ?? null,
    });

    if (narrowed === 'delivered') {
      await markReminderDelivered(ptId, status.id, ts);
    } else if (narrowed === 'failed') {
      const firstError = status.errors?.[0];
      const reason = firstError
        ? errorText(firstError)
        : 'template_delivery_failed';
      await failReminderDelivery({ ptId, wamid: status.id, reason, trace_id });
    }
  }
}

async function linkManualPatient(
  tx: DBTransaction,
  ptId: string,
  waId: string,
): Promise<void> {
  const [existing] = await tx
    .select({ id: patients.id })
    .from(patients)
    .where(and(eq(patients.ptId, ptId), eq(patients.waId, waId)))
    .limit(1);
  if (existing) return;

  const digits = waId.replace(/\D/g, '');
  if (!digits) return;
  const [manual] = await tx
    .select({ id: patients.id })
    .from(patients)
    .where(
      and(
        eq(patients.ptId, ptId),
        isNull(patients.waId),
        sql`regexp_replace(${patients.phone}, '[^0-9]', '', 'g') = ${digits}`,
      ),
    )
    .limit(1);
  if (!manual) return;

  await tx
    .update(patients)
    .set({ waId })
    .where(
      and(
        eq(patients.id, manual.id),
        eq(patients.ptId, ptId),
        isNull(patients.waId),
      ),
    );
}

function progressValue(value: unknown): number | null {
  if (typeof value === 'number' && Number.isFinite(value)) return value;
  if (typeof value === 'string') {
    const parsed = Number.parseInt(value, 10);
    if (Number.isFinite(parsed)) return parsed;
  }
  return null;
}

function errorText(
  error: NonNullable<WhatsappChangeValue['errors']>[number],
): string {
  return (
    error.message ??
    error.title ??
    error.error_data?.details ??
    `WhatsApp webhook error ${error.code ?? 'unknown'}`
  );
}

async function handleHistoryChange(
  value: WhatsappChangeValue,
  trace_id: string,
): Promise<void> {
  const connection = await loadConnectionByPhoneNumberId(
    value.metadata?.phone_number_id,
    'history',
    trace_id,
  );
  if (!connection) return;

  let syncStatus: 'syncing' | 'complete' | 'failed' | 'history_declined' =
    'syncing';
  let maxProgress: number | null = null;
  let lastError: string | null = null;

  for (const item of value.history ?? []) {
    const progress = progressValue(item.metadata?.progress);
    if (progress !== null) {
      maxProgress = Math.max(maxProgress ?? 0, progress);
    }

    for (const error of item.errors ?? []) {
      lastError = errorText(error);
      syncStatus = error.code === 2593109 ? 'history_declined' : 'failed';
    }
  }

  if (syncStatus === 'syncing' && maxProgress !== null && maxProgress >= 100) {
    syncStatus = 'complete';
  }

  await db
    .update(whatsappConnections)
    .set({
      coexistenceSyncStatus: syncStatus,
      coexistenceLastProgress: maxProgress,
      coexistenceLastError: lastError,
    })
    .where(eq(whatsappConnections.id, connection.id));
}

function parseWebhookTimestamp(input: unknown): Date {
  if (typeof input === 'number') return new Date(input * 1000);
  if (typeof input === 'string') {
    const numeric = Number.parseInt(input, 10);
    if (Number.isFinite(numeric)) return new Date(numeric * 1000);
    const parsed = new Date(input);
    if (!Number.isNaN(parsed.getTime())) return parsed;
  }
  return new Date();
}

function isDeleteAction(action: string | undefined): boolean {
  return ['delete', 'deleted', 'remove', 'removed'].includes(
    action?.toLowerCase() ?? '',
  );
}

async function handleAppStateSyncChange(
  value: WhatsappChangeValue,
  trace_id: string,
): Promise<void> {
  const connection = await loadConnectionByPhoneNumberId(
    value.metadata?.phone_number_id,
    'smb_app_state_sync',
    trace_id,
  );
  if (!connection) return;

  const log = createLogger({ trace_id });

  for (const item of value.state_sync ?? []) {
    if (item.type && item.type !== 'contact') continue;
    const contact = item.contact;
    const phone = contact?.phone_number;
    if (!phone) continue;

    const action = item.action ?? null;
    const lastSyncedAt = parseWebhookTimestamp(item.metadata?.timestamp);
    const deletedAt = isDeleteAction(item.action) ? lastSyncedAt : null;
    const waId = contact.wa_id ?? phone;
    const set = {
      phone,
      waId,
      fullName: contact.full_name ?? null,
      firstName: contact.first_name ?? null,
      sourceAction: action,
      lastSyncedAt,
      deletedAt,
    };

    // The table is unique on both (pt_id, phone) and (pt_id, wa_id) — an
    // explicit ON CONFLICT target only covers one index, so infer on wa_id
    // whenever Meta sent one (two address-book entries with differently
    // formatted phone strings resolve to the same wa_id). A collision on the
    // other index can still raise 23505; ack it per contact rather than 500 the
    // batch, which Meta would redeliver forever.
    const arbiter = contact.wa_id
      ? {
          target: [whatsappContacts.ptId, whatsappContacts.waId],
          // Required to infer the partial index (…) WHERE wa_id IS NOT NULL.
          targetWhere: isNotNull(whatsappContacts.waId),
        }
      : { target: [whatsappContacts.ptId, whatsappContacts.phone] };

    try {
      await db
        .insert(whatsappContacts)
        .values({ ptId: connection.ptId, ...set })
        .onConflictDoUpdate({ ...arbiter, set });
    } catch (err) {
      log.warn('webhook.contact_sync_failed', 'Skipping unsyncable contact', {
        pt_id: connection.ptId,
        pg_code: getPostgresErrorCode(err),
        wa_id: waId,
      });
    }
  }
}

async function contactName(ptId: string, phone: string): Promise<string> {
  const [contact] = await db
    .select({
      fullName: whatsappContacts.fullName,
      firstName: whatsappContacts.firstName,
    })
    .from(whatsappContacts)
    .where(
      and(
        eq(whatsappContacts.ptId, ptId),
        or(eq(whatsappContacts.phone, phone), eq(whatsappContacts.waId, phone)),
      ),
    )
    .limit(1);
  return contact?.fullName ?? contact?.firstName ?? phone;
}

/**
 * Bump the 24h service window and reopen a manually closed conversation. Every
 * `CASE` reads the pre-update row, so a conversation that was already open keeps
 * its AI / escalation state untouched.
 *
 * `inboundAt` is passed for inbounds we do not persist (no `messages` row means
 * no `external_id` dedupe). Meta redelivers the whole batch whenever any change
 * in the POST throws, so the reopen is keyed off the inbound's own timestamp: a
 * conversation the PT closed *after* the patient wrote stays closed however many
 * times the batch comes back.
 */
async function bumpLastInboundAt(
  tx: DBTransaction,
  conversationId: string,
  inboundAt?: Date,
): Promise<void> {
  const reopen = inboundAt
    ? sql`(${conversations.closedAt} IS NOT NULL AND ${conversations.closedAt} <= ${inboundAt.toISOString()}::timestamptz)`
    : sql`${conversations.closedAt} IS NOT NULL`;
  await tx
    .update(conversations)
    .set({
      lastInboundAt: sql`now()`,
      closedAt: sql`CASE WHEN ${reopen} THEN NULL ELSE ${conversations.closedAt} END`,
      aiActive: sql`CASE WHEN ${reopen} THEN true ELSE ${conversations.aiActive} END`,
      escalationState: sql`CASE WHEN ${reopen} THEN 'idle' ELSE ${conversations.escalationState} END`,
    })
    .where(eq(conversations.id, conversationId));
}

/** Ensure the patient + WhatsApp conversation rows exist; never touches
 *  handling state (callers own `last_inbound_at` / AI pauses). */
async function ensureWhatsappConversation(
  tx: DBTransaction,
  args: {
    ptId: string;
    waId: string;
    name: string;
  },
): Promise<{ patientId: string; conversationId: string }> {
  await linkManualPatient(tx, args.ptId, args.waId);
  await tx
    .insert(patients)
    .values({
      ptId: args.ptId,
      name: args.name,
      phone: args.waId,
      waId: args.waId,
    })
    .onConflictDoNothing({ target: [patients.ptId, patients.waId] });

  const [patient] = await tx
    .select({ id: patients.id })
    .from(patients)
    .where(and(eq(patients.ptId, args.ptId), eq(patients.waId, args.waId)))
    .limit(1);

  if (!patient) {
    throw new Error(
      `[whatsapp-webhook] patient row missing after upsert (wa_id=${args.waId})`,
    );
  }

  const insertedConversation = await tx
    .insert(conversations)
    .values({
      ptId: args.ptId,
      patientId: patient.id,
      channel: 'whatsapp',
    })
    .onConflictDoNothing({
      target: [conversations.patientId, conversations.channel],
    })
    .returning({ id: conversations.id });
  const [conversation] = insertedConversation.length
    ? insertedConversation
    : await tx
        .select({ id: conversations.id })
        .from(conversations)
        .where(
          and(
            eq(conversations.patientId, patient.id),
            eq(conversations.channel, 'whatsapp'),
          ),
        )
        .limit(1);
  if (!conversation) {
    throw new Error(
      `[whatsapp-webhook] conversation row missing after upsert (patient_id=${patient.id})`,
    );
  }

  return { patientId: patient.id, conversationId: conversation.id };
}

async function handleMessageEchoesChange(
  value: WhatsappChangeValue,
  trace_id: string,
): Promise<void> {
  const log = createLogger({ trace_id });
  const connection = await loadConnectionByPhoneNumberId(
    value.metadata?.phone_number_id,
    'smb_message_echoes',
    trace_id,
  );
  if (!connection) return;

  for (const echo of value.message_echoes ?? []) {
    if (echo.type !== 'text' || !echo.text) {
      log.warn(
        'webhook.skipping_non_text_message_echo',
        'Skipping non-text message echo',
        { type: echo.type, externalId: echo.id },
      );
      continue;
    }

    const patientWaId = echo.to;
    const name = await contactName(connection.ptId, patientWaId);
    const pauseUntil = new Date(Date.now() + 2 * 60 * 60 * 1000);

    const result = await db.transaction(async (tx) => {
      const { patientId, conversationId } = await ensureWhatsappConversation(
        tx,
        {
          ptId: connection.ptId,
          waId: patientWaId,
          name,
        },
      );

      const inserted = await tx
        .insert(messages)
        .values({
          ptId: connection.ptId,
          conversationId,
          externalId: echo.id,
          role: 'pt',
          channel: 'whatsapp',
          content: echo.text!.body,
        })
        .onConflictDoNothing({ target: messages.externalId })
        .returning({ id: messages.id });

      if (inserted.length !== 1) return { fresh: false as const };

      // Pause only after the dedupe above, so a redelivered echo cannot advance
      // `ai_paused_until` past the resume job already scheduled for it. An
      // indefinite hold the PT set themselves (`ai_active = false` with no echo
      // reason — manual takeover or an open escalation) is left alone: it must
      // not become a 2h auto-resuming pause, and `escalation_state` is never
      // cleared here.
      const stillEchoPause = sql`(${conversations.aiActive} OR ${conversations.aiPauseReason} = 'whatsapp_business_app_echo')`;
      const [paused] = await tx
        .update(conversations)
        .set({
          aiActive: false,
          aiPausedUntil: sql`CASE WHEN ${stillEchoPause} THEN ${pauseUntil.toISOString()}::timestamptz ELSE ${conversations.aiPausedUntil} END`,
          aiPauseReason: sql`CASE WHEN ${stillEchoPause} THEN 'whatsapp_business_app_echo' ELSE ${conversations.aiPauseReason} END`,
        })
        .where(eq(conversations.id, conversationId))
        .returning({ aiPauseReason: conversations.aiPauseReason });

      // No resume job for a hold we did not write — it would fire against a
      // conversation a human is still handling.
      const eventId =
        paused?.aiPauseReason === 'whatsapp_business_app_echo'
          ? await appendBackgroundEvent(tx, {
              type: 'conversation.ai_paused',
              data: {
                ptId: connection.ptId,
                conversationId,
                patientId,
                pausedUntil: pauseUntil.toISOString(),
                reason: 'whatsapp_business_app_echo',
              },
            })
          : null;
      return {
        fresh: true as const,
        eventId,
        conversationId,
        messageId: inserted[0].id,
      };
    });

    if (result.fresh) {
      if (result.eventId) await tryPublishOutboxEvent(result.eventId);
      log.info('webhook.message_accepted', 'Inbound message accepted', {
        pt_id: connection.ptId,
        conversation_id: result.conversationId,
        message_id: result.messageId,
      });
    }
  }
}

// Meta `account_update` events that leave the whole WABA unusable for sending.
// Any other event (PHONE_NUMBER_ADDED, ACCOUNT_VERIFIED, PIN_CHANGED, …) is
// informational and must not revoke a working connection. ACCOUNT_RESTRICTION is
// deliberately absent: it also covers soft restrictions (a lowered messaging
// tier, "cannot add a phone number") that leave sending fully functional, and
// re-running Embedded Signup cannot clear a revocation. PHONE_NUMBER_REMOVED is
// handled separately — it names one number, not the account.
const DISABLING_ACCOUNT_EVENTS: Record<
  string,
  'partner_removed' | 'account_disconnected'
> = {
  PARTNER_REMOVED: 'partner_removed',
  DISABLED_UPDATE: 'account_disconnected',
  ACCOUNT_VIOLATION: 'account_disconnected',
  ACCOUNT_DELETED: 'account_disconnected',
};

/** Revoke the active connections on the WABA that `extra` narrows to. */
async function revokeActiveConnections(
  wabaId: string,
  reason: 'partner_removed' | 'account_disconnected',
  extra?: SQL,
): Promise<number> {
  const connections = await db
    .select({
      id: whatsappConnections.id,
      ptId: whatsappConnections.ptId,
    })
    .from(whatsappConnections)
    .where(
      and(
        eq(whatsappConnections.wabaId, wabaId),
        eq(whatsappConnections.status, 'active'),
        ...(extra ? [extra] : []),
      ),
    );

  for (const connection of connections) {
    await markConnectionRevoked({
      connectionId: connection.id,
      ptId: connection.ptId,
      reason,
    });
  }
  return connections.length;
}

/**
 * PHONE_NUMBER_REMOVED names one number on the WABA; the others keep sending, so
 * match the payload's number against the connection instead of revoking the
 * account. Meta formats `phone_number` for display ("+1 555-123-4567"), hence the
 * digits-only comparison against `display_phone_number`.
 */
async function handlePhoneNumberRemoved(
  wabaId: string,
  value: WhatsappChangeValue,
  trace_id: string,
): Promise<void> {
  const log = createLogger({ trace_id });
  const phoneNumber = value.phone_number ?? '';
  const digits = phoneNumber.replace(/\D/g, '');
  if (!digits) {
    log.warn(
      'webhook.phone_number_removed_unmatched',
      'PHONE_NUMBER_REMOVED carried no phone number',
      { waba_id: wabaId },
    );
    return;
  }

  const revoked = await revokeActiveConnections(
    wabaId,
    'account_disconnected',
    or(
      eq(whatsappConnections.phoneNumberId, phoneNumber),
      sql`regexp_replace(COALESCE(${whatsappConnections.displayPhoneNumber}, ''), '[^0-9]', '', 'g') = ${digits}`,
    ),
  );

  if (revoked === 0) {
    log.warn(
      'webhook.phone_number_removed_unmatched',
      'No active connection matches the removed phone number',
      { waba_id: wabaId },
    );
  }
}

async function handleAccountUpdate(
  wabaId: string,
  value: WhatsappChangeValue,
  trace_id: string,
): Promise<void> {
  const log = createLogger({ trace_id });
  const event = value.event;

  if (event === 'PHONE_NUMBER_REMOVED') {
    await handlePhoneNumberRemoved(wabaId, value, trace_id);
    return;
  }

  // Worth watching (it can precede a violation) but not a disconnection: leaving
  // the connection active keeps reminders and chat sends working.
  if (event === 'ACCOUNT_RESTRICTION') {
    log.warn(
      'webhook.account_restricted',
      'Meta reported a restriction on the WABA',
      { waba_id: wabaId },
    );
    return;
  }

  const reason = event ? DISABLING_ACCOUNT_EVENTS[event] : undefined;
  if (!reason) {
    log.warn(
      'webhook.account_update_ignored',
      'Ignoring account_update event',
      { event: event ?? null, waba_id: wabaId },
    );
    return;
  }

  await revokeActiveConnections(wabaId, reason);
}
