import { describe, expect, it } from 'vitest';
import {
  DEFAULT_BUSINESS_LABEL_SQ,
  HANDOFF_ACCEPTANCE_WORD,
  isHandoffAcceptance,
} from '../handoff-offer';
import {
  NON_TEXT_PLACEHOLDER_SQ,
  nonTextContent,
  nonTextNoticeMessage,
  nonTextPlaceholder,
} from '../non-text';

describe('non-text placeholders', () => {
  it('gives every persisted non-text type a bracketed Albanian placeholder', () => {
    for (const [type, placeholder] of Object.entries(NON_TEXT_PLACEHOLDER_SQ)) {
      expect(placeholder, type).toMatch(/^\[.+\]$/);
    }
  });

  // The map is also the webhook's allowlist. A `text` entry would route a real
  // customer sentence into the fixed "I can only read text" reply instead of the
  // model — the one mapping that must never exist.
  it('has no entry for text', () => {
    expect(nonTextPlaceholder('text')).toBeNull();
  });

  // These are generated by WhatsApp or too thin to turn an unknown number into a
  // permanent entry in the professional's client directory, so they stay
  // unpersisted and unanswered.
  it.each(['reaction', 'system', 'request_welcome', 'unsupported', 'ephemeral'])(
    'ignores a %s inbound',
    (type) => {
      expect(nonTextPlaceholder(type)).toBeNull();
    },
  );

  it('names the media the customer actually sent', () => {
    expect(nonTextPlaceholder('audio')).toBe('[mesazh zanor]');
    expect(nonTextPlaceholder('image')).toBe('[foto]');
    expect(nonTextPlaceholder('document')).toBe('[dokument]');
    expect(nonTextPlaceholder('sticker')).toBe('[ngjitëse]');
  });
});

describe('nonTextContent', () => {
  it('is the bare placeholder with no caption', () => {
    expect(nonTextContent('[foto]')).toBe('[foto]');
    expect(nonTextContent('[foto]', null)).toBe('[foto]');
    expect(nonTextContent('[foto]', '   ')).toBe('[foto]');
  });

  // A caption is text the customer typed. It rides on the media object and never
  // in `text`, so before this it was dropped along with the body.
  it('keeps a caption after the placeholder', () => {
    expect(nonTextContent('[foto]', 'a mund të vij nesër?')).toBe(
      '[foto] a mund të vij nesër?',
    );
    expect(nonTextContent('[foto]', '  nesër?  ')).toBe('[foto] nesër?');
  });
});

describe('nonTextNoticeMessage', () => {
  it('says what the assistant can read and offers the handoff', () => {
    const notice = nonTextNoticeMessage('Studio Bella');
    expect(notice).toContain('vetëm mesazhe me tekst');
    expect(notice).toContain('Studio Bella');
    expect(notice).toContain(HANDOFF_ACCEPTANCE_WORD);
  });

  it('falls back to the vertical-neutral business label', () => {
    expect(nonTextNoticeMessage(DEFAULT_BUSINESS_LABEL_SQ)).toContain(
      DEFAULT_BUSINESS_LABEL_SQ,
    );
  });

  // The word the notice asks for has to be the word the resolver accepts. Two
  // modules own the two halves, so this is the seam that keeps them honest.
  it('asks for a word that actually accepts the offer', () => {
    const asked = nonTextNoticeMessage('Studio Bella')
      .split(/\s+/)
      .map((word) => word.replace(/[.,!?]$/, ''))
      .find((word) => word === HANDOFF_ACCEPTANCE_WORD);
    expect(asked).toBeDefined();
    expect(isHandoffAcceptance(asked!)).toBe(true);
  });

  // Medium books appointments for barbers and nail salons as much as for
  // physiotherapists, and it is not an emergency channel: no customer-facing
  // sentence may name a discipline or hand out urgent-care advice.
  it('names no vertical and gives no emergency guidance', () => {
    expect(nonTextNoticeMessage('Studio Bella')).not.toMatch(
      /fizioterap|klinik|mjek|urgjenc|spital|ambulanc/i,
    );
  });
});
