/**
 * Non-text inbound messages (2026-08-14). WhatsApp users send voice notes,
 * photos and documents constantly, and until now every one of them was dropped:
 * no `messages` row, so no unread badge, no chat-list preview, no realtime
 * refresh — the professional never learned the customer had written, and the
 * customer got silence.
 *
 * Two halves, deliberately split across the two runtimes that already exist:
 *
 * - The webhook persists a `messages` row whose content is a deterministic
 *   Albanian placeholder for the type (plus the caption, which WhatsApp carries
 *   on the media object and never in `text`). That single row is what restores
 *   the badge, the preview and the realtime push — all three read it.
 * - The inbound job answers once, with the fixed sentence below. The
 *   placeholder is never routed into the model: it is our own text, and a model
 *   asked to reply to `[mesazh zanor]` would invent what the voice note said.
 *
 * The reply is one of the three fixed customer sentences in `customer-copy.ts`.
 * It does not offer to pass the message on — it says the message already went to
 * the professional, which is what the `notify-non-text` push makes true.
 *
 * Telling the *professional* is the inbound job's own step (`notify-non-text`
 * in `handle-inbound-message.ts`), not this module's: it fires on every
 * non-text inbound, including the ones the day-throttle below answers with
 * `skip`, so a second photo is never silence on both sides.
 */
import { and, eq } from 'drizzle-orm';
import { conversationDayKeys } from '@/lib/billing/usage';
import { db } from '@/lib/db';
import { conversations } from '@/lib/db/schema';
import { businessLabel, nonTextNoticeMessage } from './customer-copy';
import { persistDeterministicReply } from './deterministic-reply';
import type { InboundMessage, OutboundMessage } from './types';

/**
 * The inbound `type` values that carry a customer-authored body we cannot read,
 * each with the Albanian placeholder stored in its place. This map is also the
 * webhook's allowlist of non-text types worth materialising a client and a
 * conversation for, so a type is added in exactly one place and cannot end up
 * persisted without a placeholder.
 *
 * `type` is an open string (Meta adds values), so anything absent here is
 * ignored outright: `system` (number-change notices), `reaction`,
 * `request_welcome` and `unsupported` are generated by WhatsApp or too thin to
 * turn an unknown number into a permanent entry in the professional's client
 * directory.
 */
export const NON_TEXT_PLACEHOLDER_SQ = {
  image: '[foto]',
  audio: '[mesazh zanor]',
  video: '[video]',
  document: '[dokument]',
  sticker: '[ngjitëse]',
  location: '[vendndodhje]',
  contacts: '[kontakt]',
  interactive: '[përgjigje me buton]',
  button: '[përgjigje me buton]',
  order: '[porosi]',
} as const satisfies Record<string, string>;

/** The placeholder for a non-text type, or null if the type is ignorable. */
export function nonTextPlaceholder(type: string): string | null {
  return (NON_TEXT_PLACEHOLDER_SQ as Record<string, string>)[type] ?? null;
}

/**
 * What goes in `messages.content`: the placeholder, and the caption after it
 * when the customer wrote one. Captions live on the media object — never in
 * `msg.text` — so before this they were dropped along with the message, which
 * is the worst of both worlds: the customer DID write text and got silence.
 */
export function nonTextContent(
  placeholder: string,
  caption?: string | null,
): string {
  const trimmed = caption?.trim();
  return trimmed ? `${placeholder} ${trimmed}` : placeholder;
}

/** Model marker: fixed text, no model round behind it. */
export const NON_TEXT_NOTICE_MODEL = 'deterministic-non-text-notice';

/**
 * Decide whether this non-text inbound gets the notice, and persist it if so.
 *
 * Throttled to one notice per conversation per local day, the same guard
 * `prepareCapHandoff` uses (`conversations.non_text_notice_at`): a customer who
 * fires off five voice notes in a row is told once, not five times. Per *day*
 * rather than once per conversation for good: a conversation row lives for as
 * long as the customer does, so a once-ever notice would mean the voice note
 * they send three months from now is met with the very silence this exists to
 * remove. The per-inbound AI-reply unique index makes the persist itself
 * idempotent under Inngest retries.
 */
export async function prepareNonTextNotice(args: {
  inbound: InboundMessage;
  name: string | null;
  timezone: string;
  instant: Date;
}): Promise<
  | { action: 'send'; outbound: OutboundMessage }
  | { action: 'skip'; reason: 'already_notified_today' }
> {
  const { localDay } = conversationDayKeys(args.instant, args.timezone);

  const [conversation] = await db
    .select({ nonTextNoticeAt: conversations.nonTextNoticeAt })
    .from(conversations)
    .where(
      and(
        eq(conversations.id, args.inbound.conversationId),
        eq(conversations.accountId, args.inbound.accountId),
      ),
    )
    .limit(1);

  if (conversation?.nonTextNoticeAt) {
    const noticeDay = conversationDayKeys(
      conversation.nonTextNoticeAt,
      args.timezone,
    ).localDay;
    if (noticeDay === localDay) {
      return { action: 'skip', reason: 'already_notified_today' };
    }
  }

  const outbound = await persistDeterministicReply({
    inbound: args.inbound,
    content: nonTextNoticeMessage(businessLabel(args.name)),
    model: NON_TEXT_NOTICE_MODEL,
  });
  return { action: 'send', outbound };
}

/** Record that today's notice was sent so the same day won't send another. */
export async function markNonTextNotice(args: {
  accountId: string;
  conversationId: string;
  instant: Date;
}): Promise<void> {
  await db
    .update(conversations)
    .set({ nonTextNoticeAt: args.instant })
    .where(
      and(
        eq(conversations.id, args.conversationId),
        eq(conversations.accountId, args.accountId),
      ),
    );
}
